---
- name: Rebuild postfix generic map
  command: postmap /etc/postfix/generic
- name: Reload postfix
  service:
    name: postfix
    state: reloaded
- name: Reload dovecot
  service:
    name: dovecot
    state: reloaded
- name: Reload opendkim
  service:
    name: opendkim
    state: restarted
